# -*- coding: utf-8 -*-
"""AIML_task1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yxwFEFfHv7ky3z2GNYumD27jQaOT3dHe
"""

#Import the Dataset


import pandas as pd
df = pd.read_csv('/content/archive (1).zip')
print(df.info())
print(df.describe())

#Handle Missing Values
#Identify missing data:

print(df.isnull().sum())

#Fill missing values:
df['Age'].fillna(df['Age'].median(), inplace=True)
df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)
df.drop(columns=['Cabin'], inplace=True)  # Too many nulls

#Encode Categorical Variables
df = pd.get_dummies(df, columns=['Sex', 'Embarked'], drop_first=True)

#Normalize/Standardize Features
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df[['Age', 'Fare']] = scaler.fit_transform(df[['Age', 'Fare']])

# Visualize and Remove Outliers
import seaborn as sns
import matplotlib.pyplot as plt

sns.boxplot(x=df['Fare'])
plt.show()

# Optional: remove extreme outliers
df = df[df['Fare'] < 100]

